######################################################################
# Automatically generated by qmake (3.0) Thu Jan 4 12:13:44 2018
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += autogtp.pro
